server:
  port: 9000

logging:
  level:
    root: TRACE
    '[org.springframework.web]': TRACE
    '[org.springframework.security]': TRACE
    '[org.springframework.security.oauth2]': TRACE
    
spring:
  datasource:
      url: jdbc:mariadb://localhost:3306/auth?createDatabaseIfNotExist=true
      username: root
      password: root
  jpa:
    defer-datasource-initialization: true
    hibernate:
      ddl-auto: update
    generate-ddl: false
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        '[format_sql]': true
  security:
    oauth2:
      client:
        registration:
          google-idp:
            provider: google
            client-id: ${GOOGLE_CLIENT_ID:761758187815-4rf3lv2bao9gnpgk2taei7bqfm7int8m.apps.googleusercontent.com}
            client-secret: ${GOOGLE_CLIENT_SECRET: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}
            scope: openid, https://www.googleapis.com/auth/userinfo.profile, https://www.googleapis.com/auth/userinfo.email
            client-name: oauth2-client
# No implemented
          github-idp:
            provider: github 
            client-id: ${GITHUB_CLIENT_ID:github-client-id}
            client-secret: ${GITHUB_CLIENT_SECRET:github-client-secret}
            scope: user:email, read:user
            client-name: Sign in with GitHub
        provider:
          google:
            user-name-attribute: email
          github:
            user-name-attribute: login 